 !obj:pylearn2.train.Train {
    dataset: !obj:pylearn2.datasets.mjsynth.MJSYNTH {
        which_set: 'train',
        numOfClasses: 10,
        numOfExamplesPerClass: 50
    },
    model: !obj:pylearn2.models.mlp.MLP {
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [32, 100],
            num_channels: 1,
            axes: ['c', 0, 1, 'b']
        },
        layers: [ !obj:pylearn2.models.maxout.Maxout {
                     layer_name: "l1",
                     num_units: 240,
                     num_pieces: 3,
                     max_col_norm: %(norm_l1)f,
                     sparse_init: %(init_l1)i
                 },
                 !obj:pylearn2.models.maxout.Maxout {
                     layer_name: "l2",
                     num_units: 240,
                     num_pieces: 3,
                     max_col_norm: %(norm_l2)f,
                     sparse_init: %(init_l2)i
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: %(norm_y)f,
                     layer_name: 'y',
                     n_classes: 10,
                     binary_target_dim: 1,
                     irange: %(irange_y)f
                 }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 50,
        learning_rate: %(l_r)f,
        monitoring_dataset:
            {
                'valid' : !obj:pylearn2.datasets.mjsynth.MJSYNTH {
                              which_set: 'valid',
                              numOfClasses: 10,
                              numOfExamplesPerClass: 10
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_objective",
                    prop_decrease: 0.,
                    N: 100
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 500
                }
            ]
        }
    },
}  

