!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.mjsynth.MJSYNTH {
        which_set : 'train',
        numOfClasses: 10,
        numOfExamplesPerClass: 50
    },
    model: !obj:pylearn2.models.mlp.MLP {
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [32, 100],
            num_channels: 1
        },
        layers: [ !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c1',
                     output_channels: 64,
                     irange: 0.1,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1,
                     W_lr_scale: 1,
                     border_mode: full
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c2',
                     output_channels: 128,
                     irange: 1,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1,
                     W_lr_scale: 1,
                     border_mode: full
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c3',
                     output_channels: 256,
                     irange: 1,
                     kernel_shape: [3, 3],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1,
                     W_lr_scale: 1f
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c4',
                     output_channels: 512,
                     irange: 1,
                     kernel_shape: [3, 3],
                     pool_shape: [1, 1],
                     pool_stride: [1, 1],
                     max_kernel_norm: 1,
                     W_lr_scale: 1
                 },  !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'rl',
                     dim: 4096,
                     sparse_init: 1,
                     W_lr_scale: 1
                 }, !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1,
                     layer_name: 'y',
                     n_classes: 10,
                     istdev: 1
                 }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 50,
        learning_rate: 0.1,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.1
        },
        monitoring_dataset:
            {
                'train' : !obj:pylearn2.datasets.mjsynth.MJSYNTH {
                              which_set : 'train',
                              numOfClasses: 10,
                              numOfExamplesPerClass: 50
                          },
                'valid'  : !obj:pylearn2.datasets.mjsynth.MJSYNTH {
                              which_set : 'valid',
                              numOfClasses: 10,
                              numOfExamplesPerClass: 15
                          }
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 'c1' : 1,
                                   'c2' : 1,
                                   'c3' : 1,
                                   'c4' : 1,
                                   'rl' : 1
                                 },
            input_scales: { 'c1': 1,
                            'c2': 1,
                            'c3': 1,
                            'c4': 1,
                            'rl': 1
                          }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.,
                    N: 100
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 500
                },
            ]
        },
    },
    extensions:
        [ !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 50,
            final_momentum: .5
        }
    ]
}
